# Change these first
owner: r2fo # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository
user-agent: rafo-upptime

sites:
  - name: Homepage
    url: https://r4fo.com
  - name: SearXNG
    url: https://search.r4fo.com
  - name: MiniSearch
    url: https://minisearch.r4fo.com
  - name: Whoogle
    url: https://whoogle.r4fo.com
  - name: RedLib
    url: https://redlib.r4fo.com
  - name: Nitter
    url: https://nitter.r4fo.com
  - name: GotHub
    url: https://gothub.r4fo.com/about
  - name: Anonymous Overflow
    url: https://overflow.r4fo.com
  - name: Wikiless
    url: https://wikiless.r4fo.com
  - name: Scribe
    url: https://scribe.r4fo.com
  - name: BreezeWiki
    url: https://breezewiki.r4fo.com
  - name: Quetre
    url: https://quetre.r4fo.com
  - name: LibremDB
    url: https://libremdb.r4fo.com
  - name: Mozhi
    url: https://mozhi.r4fo.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.r4fo.com
  #baseUrl: /upptime
  logoUrl: https://r4fo.com/images/site-logo.svg
  name: R4fo.com Status
  introTitle: "**R4fo.com** Services Status"
  introMessage: service status is updated every 5 minutes
  navbar:
    - title: Status
      href: /
    - title: R4FO.COM
      href: https://r4fo.com
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
